pipeline:
  changelog:
    image: bitnami/git
    commands:
      - git fetch origin master
      - git diff -wb --name-only origin/master..HEAD | grep CHANGELOG.md
    failure: ignore
  build-and-push-latest:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64, linux/arm64
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME}"
      tags: latest
    secrets: [docker_username, docker_password]
when:
  event: push
  branch: [master, main]

