steps:
  test:
    image: semtech/mu-jruby-template
    environment:
      RACK_ENV: test
    commands:
      - cp -r . /app/
      - cd /usr/src/app
      - bundle install
      - rspec
  changelog:
    image: bitnami/git
    commands:
      - git fetch origin master
      - git diff -wb --name-only origin/master..HEAD | grep CHANGELOG.md
    failure: ignore
  build-and-push-feature:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64, linux/arm64
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME}"
      tags: "feature-${CI_COMMIT_BRANCH##feature/}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: push
    branch: [feature/*]
